const t = Date.now();
const check = async (u) => { try { const r = await fetch(u + '?t=' + t, { cache: 'no-store' }); const txt = await r.text(); return { u, status: r.status, bytes: txt.length, head: txt.slice(0, 80).replace(/\s+/g, ' ') }; } catch (e) { return { u, err: String(e).slice(0, 120) }; } };
const base = 'https://shinjuku-showdown.pages.dev/';
const out = [];
for (const p of ['index.html', 'assets/game.js', 'assets/styles.css', 'assets/mobile.css', 'assets/three.js', 'sw.js']) out.push(await check(base + p));
const idx = (await check(base + 'index.html')).head;
console.log(JSON.stringify(out, null, 1));
const r = await fetch(base + 'assets/game.js?t=' + t, { cache: 'no-store' });
const g = await r.text();
console.log('GAME_TAIL', JSON.stringify(g.slice(-200)));
console.log('HAS', JSON.stringify({ Mahoraga: g.includes('MahoragaPhase'), duel: g.includes('createDomainDuel'), bf: g.includes('BlackFlash'), camFrame: g.includes('camFrame'), pressTime: g.includes('pressTime') }));
