import { Browser, sleep } from '../cdp.mjs';
import { resolve } from 'node:path';
const b = new Browser({ port: 9342, width: 800, height: 600 });
await b.launch(); await b.newPage();
b.on('Runtime.exceptionThrown', (p) => console.log('EXC', JSON.stringify(p.exceptionDetails).slice(0, 900)));
const p = resolve('_tools/_gen/artview.html');
const url = 'file:///' + p.replace(/\\/g, '/').split('/').map(encodeURIComponent).join('/');
await b.send('Page.navigate', { url });
await sleep(2500);
console.log('VIEW', await b.evaluate('typeof window.VIEW'));
console.log('bodyLen', await b.evaluate('document.body.innerHTML.length'));
console.log('logs', JSON.stringify(b.logs.slice(0,5)));
console.log('errs', JSON.stringify(b.errors.slice(0,5)));
await b.close();
