import { Browser, sleep } from '../cdp.mjs';
import { resolve } from 'node:path';
const b = new Browser({ port: 9356, width: 780, height: 800 });
await b.launch(); await b.newPage();
const p = resolve('_tools/_gen/artview.html');
await b.send('Page.navigate', { url: 'file:///' + p.replace(/\\/g, '/').split('/').map(encodeURIComponent).join('/') });
await sleep(2500);
await b.evaluate('window.VIEW.apply(' + JSON.stringify({ who: 'gojo', quality: 'high', anim: 'idle', t: 0.4, dist: 4, ty: 1 }) + ')');
await b.evaluate('window.VIEW.texSheet("gojo")');
await sleep(150);
await b.screenshot(resolve('shots/art-tex-gojo-all.png'));
console.log('errs', JSON.stringify(b.errors.slice(0,2)));
await b.close();
